export function generateMockResponse(mode: 'rag' | 'llm', userMessage: string): string {
  if (mode === 'rag') {
    return `**RAG Search Result:**

Based on your query '${userMessage}', I found relevant information in:

📄 Document: Employee Handbook.pdf
- Section 3.2: [Mock excerpt related to query]

📄 Document: Technical Guidelines.md
- Best practices for [topic from query]

Would you like me to retrieve the full documents?`
  } else {
    // LLM mode
    const paraphrase = userMessage.length > 50
      ? userMessage.substring(0, 47) + '...'
      : userMessage

    return `I understand you're asking about ${paraphrase}. Let me help with that...

This is a conversational response that addresses your question directly. In a real implementation, this would be generated by an LLM based on the context and your specific needs.

Is there anything specific you'd like me to clarify?`
  }
}
