services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - VITE_USE_MOCK_DATA=false
      - VITE_SHOW_DEVTOOLS=false
      - VITE_DIRECTUS_URL=
      - VITE_N8N_WEBHOOK_URL=
      - VITE_PORTAINER_URL=
      - VITE_PORTAINER_TOKEN=
      - VITE_PORTAINER_ENDPOINT_ID=
    restart: unless-stopped
