import type { ChatQueryPayload, WebhookResponse } from '../n8n/types'
import type { WebhookService } from '../n8n/webhook.service'

export const createMockWebhookService = (): WebhookService => ({
  sendQuery: async (payload: ChatQueryPayload, onChunk?: (text: string) => void): Promise<WebhookResponse> => {
    const { question, mode, sessionidkey } = payload

    // Log sessionidkey for debugging
    if (import.meta.env.DEV) {
      console.debug('[mock webhook] Received sessionidkey:', sessionidkey)
    }

    let fullAnswer: string
    let sources: { title: string; url: string; relevance: number }[] | undefined

    if (mode === 'rag') {
      fullAnswer = `**RAG Search Result:**

Based on your query '${question}', I found relevant information in:

📄 Document: Employee Handbook.pdf
- Section 3.2: [Mock excerpt related to query]

📄 Document: Technical Guidelines.md
- Best practices for [topic from query]

Would you like me to retrieve the full documents?`
      sources = [
        {
          title: 'Employee Handbook.pdf',
          url: '/documents/employee-handbook.pdf',
          relevance: 0.92
        },
        {
          title: 'Technical Guidelines.md',
          url: '/documents/technical-guidelines.md',
          relevance: 0.85
        }
      ]
    } else {
      // LLM mode
      const paraphrase = question.length > 50
        ? question.substring(0, 47) + '...'
        : question

      fullAnswer = `I understand you're asking about ${paraphrase}. Let me help with that...

This is a conversational response that addresses your question directly. In a real implementation, this would be generated by an LLM based on the context and your specific needs.

Is there anything specific you'd like me to clarify?`
    }

    // Simulate streaming if onChunk callback is provided
    if (onChunk) {
      const words = fullAnswer.split(' ')
      let accumulated = ''

      // Initial delay
      await new Promise(resolve => setTimeout(resolve, 500))

      // Stream word by word
      for (const word of words) {
        accumulated += (accumulated ? ' ' : '') + word
        onChunk(accumulated)
        // 50ms delay between words for realistic streaming effect
        await new Promise(resolve => setTimeout(resolve, 50))
      }
    } else {
      // No streaming, just simulate network delay
      await new Promise(resolve => setTimeout(resolve, 500))
    }

    return {
      answer: fullAnswer,
      sources
    }
  }
})
