import type { ChatQueryPayload, WebhookResponse } from '../n8n/types'
import type { WebhookService } from '../n8n/webhook.service'

export const createMockWebhookService = (): WebhookService => ({
  sendQuery: async (payload: ChatQueryPayload): Promise<WebhookResponse> => {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 500))

    const { question, mode, sessionidkey } = payload

    // Log sessionidkey for debugging
    if (import.meta.env.DEV) {
      console.debug('[mock webhook] Received sessionidkey:', sessionidkey)
    }

    if (mode === 'rag') {
      return {
        answer: `**RAG Search Result:**

Based on your query '${question}', I found relevant information in:

📄 Document: Employee Handbook.pdf
- Section 3.2: [Mock excerpt related to query]

📄 Document: Technical Guidelines.md
- Best practices for [topic from query]

Would you like me to retrieve the full documents?`,
        sources: [
          {
            title: 'Employee Handbook.pdf',
            url: '/documents/employee-handbook.pdf',
            relevance: 0.92
          },
          {
            title: 'Technical Guidelines.md',
            url: '/documents/technical-guidelines.md',
            relevance: 0.85
          }
        ]
      }
    } else {
      // LLM mode
      const paraphrase = question.length > 50
        ? question.substring(0, 47) + '...'
        : question

      return {
        answer: `I understand you're asking about ${paraphrase}. Let me help with that...

This is a conversational response that addresses your question directly. In a real implementation, this would be generated by an LLM based on the context and your specific needs.

Is there anything specific you'd like me to clarify?`
      }
    }
  }
})
